'use strict'
try{
  x=23;
}catch(error){
  console.log(error);
}

console.log('Cotinuamos');